### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by joshmedeski** [vim-conf-live/neovimconf.live#30]
Hey @nocksock 

I was unable to get this project running on my own.

1. I'm not a nix user
2. The Boring Way does not work

I got the following error when trying to get the project started
```
command not found: devenv
```

I tried following the setup instructions for installing devenv and I couldn't get past the second step (`nix-env` isn't installed on my system).

I'm guessing I'd have to get nix setup properly to get started with this project, however, I'd prefer to just get started the boring way if possible. I'd suggest setting up a `docker-compose` file for the postgres database for development, and perhaps and elixir container if we want to lock the version (I'm assuming nix has a locked version of elixir).

I'd also be down to improve the `.envrc` if we decide we want to offer the boring way fully.

**Comment by nocksock** [comment]
Solved via Discord.
